permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author:
  name: LeO
  email: totoleo@163.com
  link: http://totoleo.github.io
  weibo: http://weibo.com/2337138985
  github: http://github.com/totoleo

# 站点信息
title: 蓝
description: 对未知的渴望
url: http://totoleo.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://blog-blue.b0.upaiyun.com/20100310105627741.jpg
favicon: http://blog-blue.b0.upaiyun.com/20100310105627741.jpg!mini

# google analytics 设置
ga:
  id: UA-76790876-1
  url: totoleo.github.io

# disqus 设置
disqus:
  shortname: totoleo
