permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author:
  name: 翟晓磊
  email: totoleo@163.com
  link: http://totoleo.github.io
  weibo: http://weibo.com/2337138985
  github: http://github.com/totoleo

# 站点信息
title: 蓝
description: 对未知的渴望成就了我
url: http://totoleo.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: totoleo
